# 引入資料

In [1]:
import pandas as pd
import numpy as np

from sklearn.preprocessing import MinMaxScaler
from sklearn.metrics import accuracy_score

from sklearn.model_selection import cross_val_score, train_test_split
from sklearn.ensemble import GradientBoostingClassifier, RandomForestClassifier
from sklearn.tree import DecisionTreeClassifier, DecisionTreeRegressor

import warnings
warnings.filterwarnings('ignore')

In [2]:
data_path = 'data/'
df_train = pd.read_csv(data_path + 'train_data.csv')
df_test = pd.read_csv(data_path + 'test_features.csv')
df_train.head()

,name,bonus,deferral_payments,deferred_income,director_fees,email_address,exercised_stock_options,expenses,from_messages,from_poi_to_this_person,...,long_term_incentive,other,poi,restricted_stock,restricted_stock_deferred,salary,shared_receipt_with_poi,to_messages,total_payments,total_stock_value
0,RICE KENNETH D,1750000.0,NaN,-3504386.0,NaN,ken.rice@enron.com,19794175.0,46950.0,18.0,42.0,...,1617011.0,174839.0,True,2748364.0,NaN,420636.0,864.0,905.0,505050.0,22542539.0
1,SKILLING JEFFREY K,5600000.0,NaN,NaN,NaN,jeff.skilling@enron.com,19250000.0,29336.0,108.0,88.0,...,1920000.0,22122.0,True,6843672.0,NaN,1111258.0,2042.0,3627.0,8682716.0,26093672.0
2,SHELBY REX,200000.0,NaN,-4167.0,NaN,rex.shelby@enron.com,1624396.0,22884.0,39.0,13.0,...,NaN,1573324.0,True,869220.0,NaN,211844.0,91.0,225.0,2003885.0,2493616.0
3,KOPPER MICHAEL J,800000.0,NaN,NaN,NaN,michael.kopper@enron.com,NaN,118134.0,NaN,NaN,...,602671.0,907502.0,True,985032.0,NaN,224305.0,NaN,NaN,2652612.0,985032.0
4,CALGER CHRISTOPHER F,1250000.0,NaN,-262500.0,NaN,christopher.calger@enron.com,NaN,35818.0,144.0,199.0,...,375304.0,486.0,True,126027.0,NaN,240189.0,2188.0,2598.0,1639297.0,126027.0

In [3]:
df_train.describe()

,bonus,deferral_payments,deferred_income,director_fees,exercised_stock_options,expenses,from_messages,from_poi_to_this_person,from_this_person_to_poi,loan_advances,long_term_incentive,other,restricted_stock,restricted_stock_deferred,salary,shared_receipt_with_poi,to_messages,total_payments,total_stock_value
count,6.100000e+01,2.800000e+01,3.400000e+01,13.000000,8.100000e+01,73.000000,65.000000,65.000000,65.000000,2.000000e+00,4.900000e+01,6.900000e+01,8.200000e+01,10.000000,7.300000e+01,65.000000,65.000000,9.600000e+01,9.800000e+01
mean,1.147436e+06,6.344374e+05,-4.625664e+05,89397.846154,2.985081e+06,51040.547945,711.323077,64.800000,40.092308,4.096250e+07,7.926171e+05,4.471774e+05,1.294855e+06,-221885.700000,2.739025e+05,1111.369231,2156.061538,2.590977e+06,3.527136e+06
std,1.505189e+06,8.603646e+05,8.095392e+05,41143.391399,6.004174e+06,47596.682104,2074.497628,91.863214,88.901407,5.736404e+07,9.504645e+05,1.341564e+06,2.498335e+06,205191.374121,1.716647e+05,1165.852016,2811.676718,1.056645e+07,7.182997e+06
min,7.000000e+04,-1.025000e+05,-3.504386e+06,3285.000000,3.285000e+03,148.000000,12.000000,0.000000,0.000000,4.000000e+05,7.102300e+04,2.000000e+00,4.409300e+04,-560222.000000,4.770000e+02,2.000000,57.000000,1.480000e+02,-4.409300e+04
25%,4.500000e+05,7.656750e+04,-5.527032e+05,101250.000000,4.004780e+05,18834.000000,19.000000,10.000000,0.000000,2.068125e+07,2.750000e+05,9.720000e+02,2.689220e+05,-389621.750000,2.061210e+05,178.000000,517.000000,3.024025e+05,4.211518e+05
50%,7.500000e+05,1.951900e+05,-1.175340e+05,108579.000000,8.500100e+05,41953.000000,45.000000,28.000000,7.000000,4.096250e+07,4.221580e+05,5.238200e+04,4.628225e+05,-139856.500000,2.516540e+05,599.000000,1088.000000,1.106740e+06,9.979710e+05
75%,1.000000e+06,8.342052e+05,-2.708325e+04,112492.000000,2.165172e+06,59175.000000,215.000000,88.000000,27.000000,6.124375e+07,8.318090e+05,3.620960e+05,9.664905e+05,-77953.250000,2.885890e+05,1902.000000,2649.000000,1.985668e+06,2.493616e+06
max,8.000000e+06,2.964506e+06,-1.042000e+03,125034.000000,3.434838e+07,228763.000000,14368.000000,528.000000,411.000000,8.152500e+07,5.145434e+06,1.035973e+07,1.476169e+07,44093.000000,1.111258e+06,4527.000000,15149.000000,1.035598e+08,4.911008e+07

In [4]:
df_train['poi'] = df_train['poi'].astype(float)
train_Y = df_train['poi']
ids = df_test['name']

df_train = df_train.drop(['name', 'email_address', 'poi'] , axis=1)
df_test = df_test.drop(['name', 'email_address'] , axis=1)

df = pd.concat([df_train, df_test])
df

,bonus,deferral_payments,deferred_income,director_fees,exercised_stock_options,expenses,from_messages,from_poi_to_this_person,from_this_person_to_poi,loan_advances,long_term_incentive,other,restricted_stock,restricted_stock_deferred,salary,shared_receipt_with_poi,to_messages,total_payments,total_stock_value
0,1750000.0,NaN,-3504386.0,NaN,19794175.0,46950.0,18.0,42.0,4.0,NaN,1617011.0,174839.0,2748364.0,NaN,420636.0,864.0,905.0,505050.0,22542539.0
1,5600000.0,NaN,NaN,NaN,19250000.0,29336.0,108.0,88.0,30.0,NaN,1920000.0,22122.0,6843672.0,NaN,1111258.0,2042.0,3627.0,8682716.0,26093672.0
2,200000.0,NaN,-4167.0,NaN,1624396.0,22884.0,39.0,13.0,14.0,NaN,NaN,1573324.0,869220.0,NaN,211844.0,91.0,225.0,2003885.0,2493616.0
3,800000.0,NaN,NaN,NaN,NaN,118134.0,NaN,NaN,NaN,NaN,602671.0,907502.0,985032.0,NaN,224305.0,NaN,NaN,2652612.0,985032.0
4,1250000.0,NaN,-262500.0,NaN,NaN,35818.0,144.0,199.0,25.0,NaN,375304.0,486.0,126027.0,NaN,240189.0,2188.0,2598.0,1639297.0,126027.0
5,NaN,10259.0,NaN,NaN,30766064.0,77978.0,NaN,NaN,NaN,NaN,NaN,2856.0,NaN,NaN,NaN,NaN,NaN,91093.0,30766064.0
6,NaN,NaN,NaN,NaN,8308552.0,53947.0,NaN,NaN,NaN,NaN,NaN,147950.0,3576206.0,NaN,158403.0,NaN,NaN,360300.0,11884758.0
7,1200000.0,27610.0,-144062.0,NaN,NaN,16514.0,40.0,240.0,11.0,NaN,NaN,101740.0,698242.0,NaN,288542.0,1132.0,1758.0,1490344.0,698242.0
8,7000000.0,202911.0,-300000.0,NaN,34348384.0,99832.0,36.0,123.0,16.0,81525000.0,3600000.0,10359729.0,14761694.0,NaN,1072321.0,2411.0,4273.0,103559793.0,49110078.0
9,600000.0,NaN,NaN,NaN,384728.0,125978.0,16.0,52.0,6.0,NaN,71023.0,200308.0,393818.0,NaN,274975.0,874.0,873.0,1272284.0,778546.0
10,700000.0,NaN,NaN,NaN,671737.0,127017.0,61.0,53.0,15.0,NaN,300000.0,150458.0,1248318.0,NaN,309946.0,2271.0,2374.0,1587421.0,1920055.0
11,700000.0,214678.0,-100000.0,NaN,1635238.0,33271.0,82.0,35.0,48.0,NaN,NaN,1950.0,283649.0,NaN,249201.0,1258.0,1328.0,1099100.0,1918887.0
12,1300000.0,NaN,-1386055.0,NaN,NaN,55921.0,NaN,NaN,NaN,NaN,1736055.0,277464.0,1794412.0,NaN,440698.0,NaN,NaN,2424083.0,1794412.0
13,750000.0,NaN,NaN,NaN,436515.0,NaN,NaN,NaN,NaN,NaN,304805.0,819288.0,441096.0,NaN,272880.0,NaN,NaN,2146973.0,877611.0
14,4175000.0,2869717.0,-3081055.0,NaN,1729541.0,13868.0,2195.0,47.0,65.0,NaN,304805.0,152.0,126027.0,-126027.0,201955.0,1407.0,2902.0,4484442.0,1729541.0
15,850000.0,NaN,NaN,NaN,765313.0,84208.0,14.0,25.0,2.0,NaN,831809.0,272.0,189041.0,NaN,248546.0,2326.0,2475.0,2014835.0,954354.0
16,509870.0,73122.0,-1042.0,NaN,83237.0,50080.0,NaN,NaN,NaN,NaN,NaN,76547.0,235370.0,NaN,192008.0,NaN,NaN,900585.0,318607.0
17,NaN,NaN,NaN,NaN,139130.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,139130.0
18,325000.0,NaN,NaN,NaN,NaN,22344.0,NaN,NaN,NaN,NaN,275000.0,713.0,207940.0,NaN,184899.0,NaN,NaN,807956.0,207940.0
19,1000000.0,NaN,NaN,NaN,NaN,NaN,63.0,67.0,14.0,NaN,1387399.0,3083.0,360528.0,NaN,273746.0,2672.0,2822.0,2664228.0,360528.0
20,NaN,16586.0,NaN,NaN,4452476.0,46145.0,41.0,0.0,0.0,NaN,200000.0,426629.0,365320.0,NaN,222093.0,73.0,266.0,911453.0,4817796.0
21,NaN,NaN,NaN,NaN,5266578.0,18834.0,NaN,NaN,NaN,NaN,135836.0,176.0,2041016.0,NaN,94941.0,NaN,NaN,249787.0,7307594.0
22,500000.0,NaN,NaN,NaN,825464.0,600.0,125.0,0.0,0.0,NaN,304805.0,1215.0,189041.0,NaN,248017.0,23.0,1088.0,1054637.0,1014505.0
23,NaN,NaN,NaN,NaN,757301.0,NaN,13.0,54.0,1.0,NaN,NaN,NaN,934065.0,NaN,NaN,720.0,894.0,NaN,1691366.0
24,NaN,NaN,NaN,NaN,651850.0,NaN,12.0,10.0,0.0,NaN,NaN,NaN,386335.0,NaN,NaN,58.0,764.0,NaN,1038185.0
25,NaN,NaN,NaN,NaN,1753766.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,264013.0,-72419.0,NaN,NaN,NaN,NaN,1945360.0
26,3100000.0,NaN,NaN,NaN,81042.0,5774.0,1728.0,251.0,194.0,NaN,NaN,93925.0,466101.0,NaN,271442.0,3669.0,8305.0,3471141.0,547143.0
27,NaN,NaN,-17500.0,17500.0,NaN,NaN,26.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,12.0,653.0,NaN,NaN
28,70000.0,NaN,NaN,NaN,NaN,28164.0,14.0,10.0,3.0,NaN,NaN,774.0,NaN,NaN,221003.0,114.0,176.0,319941.0,NaN
29,400000.0,NaN,NaN,NaN,850010.0,83585.0,14368.0,41.0,171.0,NaN,323466.0,4669.0,126027.0,NaN,275101.0,583.0,4607.0,1086821.0,976037.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3,3000000.0,NaN,NaN,NaN,2291113.0,86174.0,3069.0,66.0,609.0,NaN,1294981.0,1661.0,1323148.0,NaN,365163.0,2097.0,3093.0,4747979.0,3614261.0
4,1000000.0,NaN,-235000.0,NaN,NaN,30674.0,49.0,58.0,12.0,NaN,350000.0,307895.0,2502063.0,NaN,415189.0,1585.0,1892.0,1868758.0,2502063.0
5,1700000.0,NaN,NaN,NaN,NaN,98849.0,27.0,40.0,1.0,NaN,69223.0,1936.0,441096.0,NaN,211788.0,900.0,1320.0,2081796.0,441096.0
6,2000000.0,6426990.0,-3367011.0,NaN,10433518.0,86987.0,21.0,242.0,6.0,2000000.0,1617011.0,7427621.0,4188667.0,NaN,1060932.0,2979.0,3275.0,17252530.0,14622185.0
7,NaN,NaN,-98784.0,98784.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,32460.0,-32460.0,NaN,NaN,NaN,NaN,NaN
8,800000.0,NaN,-300000.0,NaN,765920.0,96268.0,22.0,188.0,11.0,NaN,NaN,891.0,315068.0,NaN,278601.0,772.0,865.0,875760.0,1080988.0
9,100000.0,51365.0,-200000.0,NaN,4160672.0,8409.0,NaN,NaN,NaN,NaN,156250.0,202052.0,201483.0,-140264.0,76399.0,NaN,NaN,394475.0,4221891.0
10,NaN,3131860.0,NaN,NaN,5210569.0,NaN,1073.0,44.0,15.0,NaN,NaN,NaN,2046079.0,NaN,NaN,1074.0,2350.0,3131860.0,7256648.0
11,NaN,NaN,NaN,NaN,850477.0,NaN,26.0,10.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,739.0,952.0,NaN,850477.0
12,NaN,NaN,NaN,NaN,1426469.0,NaN,25.0,39.0,18.0,NaN,NaN,NaN,405999.0,NaN,NaN,583.0,613.0,NaN,1832468.0
13,NaN,NaN,-38346.0,38346.0,NaN,2151.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2151.0,NaN
14,800000.0,NaN,-1284000.0,NaN,8831913.0,51124.0,909.0,64.0,20.0,NaN,484000.0,7482.0,1787380.0,-1787380.0,492375.0,1401.0,2181.0,550981.0,8831913.0
15,NaN,NaN,NaN,NaN,NaN,NaN,16.0,0.0,1.0,NaN,NaN,NaN,47304.0,NaN,NaN,3.0,58.0,NaN,47304.0
16,425000.0,875307.0,-775241.0,NaN,2027865.0,52255.0,NaN,NaN,NaN,NaN,415657.0,1105.0,315068.0,-315068.0,210500.0,NaN,NaN,1204583.0,2027865.0
17,NaN,NaN,-51042.0,NaN,NaN,116335.0,NaN,NaN,NaN,NaN,NaN,465357.0,1034346.0,NaN,174246.0,NaN,NaN,704896.0,1034346.0
18,400000.0,260455.0,-201641.0,NaN,NaN,129142.0,NaN,NaN,NaN,NaN,NaN,69.0,145796.0,-82782.0,239671.0,NaN,NaN,827696.0,63014.0
19,NaN,564348.0,NaN,NaN,886231.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,208809.0,NaN,NaN,NaN,NaN,564348.0,1095040.0
20,97343619.0,32083396.0,-27992891.0,1398517.0,311764000.0,5235198.0,NaN,NaN,NaN,83925000.0,48521928.0,42667589.0,130322299.0,-7576788.0,26704229.0,NaN,NaN,309886585.0,434509511.0
21,2500000.0,NaN,NaN,NaN,940257.0,95924.0,75.0,42.0,37.0,NaN,374347.0,401481.0,1392142.0,NaN,304588.0,1604.0,1755.0,3676340.0,2332399.0
22,600000.0,NaN,NaN,NaN,NaN,94299.0,29.0,38.0,1.0,NaN,NaN,1740.0,585062.0,NaN,365788.0,702.0,807.0,1061827.0,585062.0
23,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,189583.0,NaN,NaN,NaN,NaN,NaN,189583.0,NaN
24,325000.0,NaN,NaN,NaN,NaN,35018.0,NaN,NaN,NaN,NaN,NaN,1411.0,208510.0,NaN,267093.0,NaN,NaN,628522.0,208510.0
25,300000.0,NaN,-159792.0,NaN,NaN,NaN,15.0,29.0,7.0,NaN,75000.0,540.0,307301.0,-307301.0,261809.0,196.0,312.0,477557.0,NaN
26,NaN,NaN,NaN,137864.0,2604490.0,NaN,29.0,0.0,1.0,NaN,NaN,137864.0,-2604490.0,15456290.0,NaN,463.0,523.0,15456290.0,NaN
27,NaN,53625.0,NaN,NaN,1030329.0,33785.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,87410.0,1030329.0
28,1000000.0,NaN,NaN,NaN,1465734.0,38559.0,40.0,23.0,8.0,NaN,369721.0,425688.0,378082.0,NaN,213625.0,1336.0,1607.0,2047593.0,1843816.0
29,1500000.0,NaN,NaN,NaN,1835558.0,NaN,92.0,28.0,23.0,NaN,554422.0,1852186.0,1293424.0,NaN,428780.0,2103.0,3187.0,4335388.0,3128982.0
30,NaN,504610.0,NaN,NaN,2218275.0,NaN,12.0,0.0,0.0,NaN,461912.0,NaN,NaN,NaN,NaN,23.0,169.0,966522.0,2218275.0
31,200000.0,204075.0,NaN,NaN,2549361.0,57727.0,NaN,NaN,NaN,NaN,175000.0,2630.0,514847.0,NaN,236457.0,NaN,NaN,875889.0,3064208.0
32,2600000.0,NaN,NaN,NaN,1104054.0,137108.0,48.0,58.0,26.0,NaN,694862.0,297353.0,558801.0,NaN,370448.0,2228.0,2355.0,4099771.0,1662855.0

# 補缺失值

In [5]:
# 查看缺失值情況
def na_check(df_data):
    na = (df_data.isnull().sum() / len(df_data))*100
    na = na.drop(na[na==0].index).sort_values(ascending=False)
    missing_data = pd.DataFrame({'Missing Ratio': na})
    display(missing_data.head(10))
na_check(df)

                           Missing Ratio
loan_advances                  97.260274
director_fees                  88.356164
restricted_stock_deferred      87.671233
deferral_payments              73.287671
deferred_income                66.438356
long_term_incentive            54.794521
bonus                          43.835616
from_this_person_to_poi        41.095890
from_poi_to_this_person        41.095890
from_messages                  41.095890

In [6]:
# loan_advances(高額貸款)缺值補0
df["loan_advances"] = df["loan_advances"].fillna(0)

In [7]:
# director_fees 補0
df["director_fees"] = df["director_fees"].fillna(0)

In [8]:
# restricted_stock_deferred 補0
df["restricted_stock_deferred"] = df["restricted_stock_deferred"].fillna(0)

In [9]:
# deferral_payments 補0
df["deferral_payments"] = df["deferral_payments"].fillna(0)

In [10]:
# deferred_income 補0
df["deferred_income"] = df["deferred_income"].fillna(0)

In [11]:
# long_term_incentive 補0
df["long_term_incentive"] = df["long_term_incentive"].fillna(0)

In [12]:
# bonus 補0
bonus_fillna = df["bonus"].fillna(0)
bonus_median = np.median(bonus_fillna)
df["bonus"] = df["bonus"].fillna(bonus_median)

In [13]:
# from_this_person_to_poi 補0
df["from_this_person_to_poi"] = df["from_this_person_to_poi"].fillna(0)

In [14]:
# from_poi_to_this_person 補0
df["from_poi_to_this_person"] = df["from_poi_to_this_person"].fillna(0)

In [15]:
# from_messages 補0
df["from_messages"] = df["from_messages"].fillna(0)

In [16]:
na_check(df)

                         Missing Ratio
to_messages                  41.095890
shared_receipt_with_poi      41.095890
other                        36.301370
salary                       34.931507
expenses                     34.931507
exercised_stock_options      30.136986
restricted_stock             24.657534
total_payments               14.383562
total_stock_value            13.698630

In [17]:
df = df.fillna(0)

In [18]:
na_check(df)

Empty DataFrame
Columns: [Missing Ratio]
Index: []

In [19]:
df.describe()

,bonus,deferral_payments,deferred_income,director_fees,exercised_stock_options,expenses,from_messages,from_poi_to_this_person,from_this_person_to_poi,loan_advances,long_term_incentive,other,restricted_stock,restricted_stock_deferred,salary,shared_receipt_with_poi,to_messages,total_payments,total_stock_value
count,1.460000e+02,1.460000e+02,1.460000e+02,1.460000e+02,1.460000e+02,1.460000e+02,146.000000,146.000000,146.000000,1.460000e+02,1.460000e+02,1.460000e+02,1.460000e+02,1.460000e+02,1.460000e+02,146.000000,146.000000,1.460000e+02,1.460000e+02
mean,1.464981e+06,4.387965e+05,-3.827622e+05,1.942249e+04,4.182736e+06,7.074827e+04,358.602740,38.226027,24.287671,1.149658e+06,6.646839e+05,5.854318e+05,1.749257e+06,2.051637e+04,3.658114e+05,692.986301,1221.589041,4.350622e+06,5.846018e+06
std,8.073567e+06,2.741325e+06,2.378250e+06,1.190543e+05,2.607040e+07,4.327163e+05,1441.259868,73.901124,79.278206,9.649342e+06,4.046072e+06,3.682345e+06,1.089995e+07,1.439661e+06,2.203575e+06,1072.969492,2226.770637,2.693448e+07,3.624681e+07
min,7.000000e+04,-1.025000e+05,-2.799289e+07,0.000000e+00,0.000000e+00,0.000000e+00,0.000000,0.000000,0.000000,0.000000e+00,0.000000e+00,0.000000e+00,-2.604490e+06,-7.576788e+06,0.000000e+00,0.000000,0.000000,0.000000e+00,-4.409300e+04
25%,3.000000e+05,0.000000e+00,-3.792600e+04,0.000000e+00,0.000000e+00,0.000000e+00,0.000000,0.000000,0.000000,0.000000e+00,0.000000e+00,0.000000e+00,8.115000e+03,0.000000e+00,0.000000e+00,0.000000,0.000000,9.394475e+04,2.288695e+05
50%,3.000000e+05,0.000000e+00,0.000000e+00,0.000000e+00,6.082935e+05,2.018200e+04,16.500000,2.500000,0.000000,0.000000e+00,0.000000e+00,9.595000e+02,3.605280e+05,0.000000e+00,2.105960e+05,102.500000,289.000000,9.413595e+05,9.659550e+05
75%,8.000000e+05,9.684500e+03,0.000000e+00,0.000000e+00,1.714221e+06,5.374075e+04,51.250000,40.750000,13.750000,0.000000e+00,3.750648e+05,1.506065e+05,8.145280e+05,0.000000e+00,2.708505e+05,893.500000,1585.750000,1.968287e+06,2.319991e+06
max,9.734362e+07,3.208340e+07,0.000000e+00,1.398517e+06,3.117640e+08,5.235198e+06,14368.000000,528.000000,609.000000,8.392500e+07,4.852193e+07,4.266759e+07,1.303223e+08,1.545629e+07,2.670423e+07,5521.000000,15149.000000,3.098866e+08,4.345095e+08

# 拆分資料

In [20]:
train_num = train_Y.shape[0]
train_X = df[:train_num]
test_X = df[train_num:]

In [21]:
x_train, x_test, y_train, y_test = train_test_split(train_X, train_Y, test_size=0.25, random_state=4)
x_train.shape, x_test.shape, y_train.shape, y_test.shape

((84, 19), (29, 19), (84,), (29,))

# 訓練模型、測試

## NAIBE BAYES

In [25]:
# NAIBE BAYES
from sklearn.naive_bayes import GaussianNB
model = GaussianNB()
model.fit(x_train, y_train) #ravel()轉一維 #訓練模型
predicted = model.predict(x_test) #用test set進行預測
print('Naive Bayes',accuracy_score(y_test, predicted))

Naive Bayes 0.896551724137931

## GradientBoostingClassifier

In [26]:
from sklearn.ensemble import GradientBoostingClassifier
gdbt_model = GradientBoostingClassifier()
gdbt_model.fit(x_train, y_train)
predicted = model.predict(x_test)
print('GradientBoostingClassifier',accuracy_score(y_test, predicted))

GradientBoostingClassifier 0.896551724137931

## KNeighborsClassifier

In [27]:
# KNN
from sklearn.neighbors import KNeighborsClassifier
knn_model = KNeighborsClassifier()
knn_model.fit(x_train, y_train.values.ravel())
predicted = knn_model.predict(x_test)
print('KNN', accuracy_score(y_test, predicted))

KNN 0.8620689655172413

## RANDOM FOREST

In [28]:
from sklearn.ensemble import RandomForestClassifier
rfc_model = RandomForestClassifier(n_estimators = 100, max_depth=4, random_state = 99)
rfc_model.fit(x_train, y_train.values.ravel())
predicted = rfc_model.predict(x_test)
print('Random Forest', accuracy_score(y_test, predicted))

Random Forest 0.8620689655172413

## LOGISTIC REGRESSION

In [29]:
from sklearn.linear_model import LogisticRegression
lr_model = LogisticRegression(solver = 'saga') #solver:優化器選擇，default=’lbfgs’
lr_model.fit(x_train,y_train.values.ravel())
lr_predicted = lr_model.predict(x_test)
print('Logistic Regression',accuracy_score(y_test, lr_predicted))

Logistic Regression 0.8620689655172413

## SVM

In [30]:
#SVM
from sklearn.svm import SVC
svc_model = SVC(gamma = 'auto')
svc_model.fit(x_train,y_train.values.ravel())
svc_predicted = svc_model.predict(x_test)
print('SVM',accuracy_score(y_test, svc_predicted))

SVM 0.8620689655172413

## DECISON TREE

In [31]:
#DECISON TREE
from sklearn.tree import DecisionTreeClassifier
dtree_model = DecisionTreeClassifier()
dtree_model.fit(x_train, y_train.values.ravel())
dtree_predicted = dtree_model.predict(x_test)
print('Decision Tree', accuracy_score(y_test, dtree_predicted))

Decision Tree 0.7931034482758621

## XGBOOST

In [32]:
#XGBOOST
from xgboost import XGBClassifier
xgb = XGBClassifier()
xgb.fit(x_train,y_train.values.ravel())
xgb_predicted = xgb.predict(x_test)
print('XGBoost',accuracy_score(y_test, xgb_predicted))

ModuleNotFoundError: No module named 'xgboost'

# 匯出CSV提交

In [35]:
gdbt_model.fit(x_train, y_train)
gdbt_predict = gdbt_model.predict(test_X)
sub = pd.DataFrame({'name': ids, 'poi': gdbt_predict})
sub.to_csv('result.csv', index=False)